# Generated by Django 3.2.5 on 2021-07-19 10:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='製品名')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='注文日')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.product', verbose_name='製品名')),
            ],
            options={
                'verbose_name': '注文データ',
                'verbose_name_plural': '注文データ',
            },
        ),
    ]
